### ISSUE TITLE
do we need virtual environment command like venv to use to bot on ubuntu?

### ISSUE THREAD

**Issue by icsan44** [flaming-chameleon/telegram-blum-auto#1]
cant install the script because the error for requirment install 
Error: 
To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
how to fix?

**Comment by icsan44** [comment]
i try on windows and its got error like this
![Uploading Untitled.png…]()

**Comment by icsan44** [comment]
note i use windows 10 for this, but for ubuntu 24.04 TLS cant install the script because the error for requirment install

**Comment by flaming-chameleon** [comment]
"requirment install" give me screen of that

**Comment by icsan44** [comment]
![image](https://github.com/flaming-chameleon/telegram-blum-auto/assets/57229555/4fd69407-2ee6-4a13-9fce-cd48a982c42f)

Note : its ubuntu 24.04 TLS

**Comment by icsan44** [comment]
> ![Untitled](https://private-user-images.githubusercontent.com/57229555/334148973-57a12a9b-2e20-47a1-aa85-f3e8fa9f7967.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MjQ1MDAsIm5iZiI6MTcxNjgyNDIwMCwicGF0aCI6Ii81NzIyOTU1NS8zMzQxNDg5NzMtNTdhMTJhOWItMmUyMC00N2ExLWFhODUtZjNlOGZhOWY3OTY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDE1MzY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5ODI2OWRhODE3N2M2YzJmMzFmZDlhNWZiMTY1ODZmZjc3OTM3M2JlYzU3NTExZjZjZDk3YzQ2NDRlYWEyM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6ZYcZa0cDDXBxaHeAH3bmyxTWnaWhtgG9Rq-hgdRYxg)

this is from windows 10, the requirement install is good but error when play soft

**Comment by flaming-chameleon** [comment]
try pip3 not pip

pip3 for python3 (version 3+)
pip for python2 which not supported

**Comment by icsan44** [comment]
> try pip3 not pip
> 
> pip3 for python3 (version 3+) pip for python2 which not supported

already done that, the same error

**Comment by icsan44** [comment]
> try pip3 not pip
> 
> pip3 for python3 (version 3+) pip for python2 which not supported

trying using python3 -m venv venv
still the same error

**Comment by flaming-chameleon** [comment]
than dont do venv, ignore it and just install

**Comment by icsan44** [comment]
![image](https://github.com/flaming-chameleon/telegram-blum-auto/assets/57229555/c006767a-4d78-45f2-89e1-5779d7f738c0)

**Comment by flaming-chameleon** [comment]
Join this chat and send your error in chat. We will help you
https://t.me/hidden_codding_chat
