### ISSUE TITLE
Перестает работать бот 

### ISSUE THREAD

**Issue by DanielCodeWeb** [flaming-chameleon/telegram-blum-auto#10]
Примерно на 3 раз как появляется зеленая кнопка сбор монет, бот перестает их собирать в консоле такой лог.
![Screenshot_1 копия](https://github.com/flaming-chameleon/telegram-blum-auto/assets/75091602/3ff3f24d-36de-4027-801a-08962786d067)

**Comment by mesteruh** [comment]
@GoldenBroPro как воспроизвести?

**Comment by lrdcxdes** [comment]
+

**Comment by WubbaLubbaDubDubDev** [comment]
Аналогичная проблема

**Comment by hashedvoid** [comment]
также
