### ISSUE TITLE
Bot stopping

### ISSUE THREAD

**Issue by byanonim** [flaming-chameleon/telegram-blum-auto#17]
When you run the application in the background on Ubuntu with the screen command, it gets stuck and closes when you want to farm for the second time. How can we solve the problem?
![IMG_20240603_225725](https://github.com/flaming-chameleon/telegram-blum-auto/assets/11058116/aea608ab-5bc1-460a-8d72-db47ac4a53ef)

**Comment by AlexKrutoy** [comment]
Hello

Update ur bot by redownloading zip or git pull

I commited new update which fix this error
