### ISSUE TITLE
game play is not working

### ISSUE THREAD

**Issue by faizahmaddae** [flaming-chameleon/telegram-blum-auto#20]
game play is not working

**Comment by vladbogun1** [comment]
yes, same for me, yesturday i just restarted bot 10 times and finally played, today all requests failed
![image](https://github.com/flaming-chameleon/telegram-blum-auto/assets/34967580/97bf9621-172d-4329-abc2-17909905c3f1)

**Comment by XPacL** [comment]
Други, сервера Блума лежат в связи с возможностью добавлять 10 друзей... Ждите, починят, или перезапускайте бота при ошибке, авось повезёт

**Comment by Raxmatilla97** [comment]
Error: Cannot connect to host game-domain.blum.codes:443 ssl:default [The semaphore timeout period has expired]
Значит SSL не работает на домене?

**Comment by vladbogun1** [comment]
> Error: Cannot connect to host game-domain.blum.codes:443 ssl:default [The semaphore timeout period has expired] Значит SSL не работает на домене?

вчера pull request был который это чинит

https://github.com/flaming-chameleon/telegram-blum-auto/pull/19

**Comment by Raxmatilla97** [comment]
Спасибо, не помогло, когда обновил, сейчас клонировал еще раз и все заработало.
