### ISSUE TITLE
Как подключить прокси?

### ISSUE THREAD

**Issue by Raxmatilla97** [flaming-chameleon/telegram-blum-auto#21]
С какого сайта и как можно подключить прокси? Действительно ли нужен прокси, чтобы Blumне забанил?

**Comment by XPacL** [comment]
Зависит от того сколько аккаунтов хочешь гонять

**Comment by Raxmatilla97** [comment]
20+ аккаунт

**Comment by flaming-chameleon** [comment]
https://t.me/hidden_codding_chat/16053 все вопросы задавайте тут
