### ISSUE TITLE
Session error

### ISSUE THREAD

**Issue by berezenko04** [flaming-chameleon/telegram-blum-auto#22]
12:10:29.78 | INFO | Searched sessions: 1!
12:10:29.78 | INFO | Checking sessions...
12:10:31.21 | SUCCESS | Valid sessions: 1; Invalid: 0
12:10:31.21 | ERROR | 1 | Session error: list index out of range
12:10:31.21 | INFO | 1 | Reconnecting, 61 s
12:11:32.21 | ERROR | 1 | Session error: list index out of range
12:11:32.21 | INFO | 1 | Reconnecting, 61 s

**Comment by AlexKrutoy** [comment]
Join chat and ask for help
