### ISSUE TITLE
[ Bug ] There is a problem with multiaccount or proxy

### ISSUE THREAD

**Issue by ZeroParadoxHome** [flaming-chameleon/telegram-blum-auto#24]
Hello i am trying to use script with 3 sessions and socks5 proxies but i encounter an error:

09:19:27.91 | INFO | Checking sessions...
09:19:33.80 | SUCCESS | Valid sessions: 3; Invalid: 0
09:19:33.81 | ERROR | X1 | Session error: list index out of range
09:19:33.81 | INFO | X1 | Reconnecting, 61 s
09:19:33.81 | ERROR | X2 | Session error: list index out of range
09:19:33.82 | INFO | X2 | Reconnecting, 61 s
09:19:33.82 | ERROR | X3 | Session error: list index out of range
09:19:33.83 | INFO | X3 | Reconnecting, 61 s

Note: yesterday I launched script with one session and proxy dedicated to it and it worked fine
Today i added to more sessions and two other proxies dedicated to them but it's not working
Also when i change the Proxy variable to False its starts working

**Comment by nartyjezusa** [comment]
did you find out whats wrong?
